[book]
authors = ["Pistonight"]
title = "Workex"

[output.html]
default-theme = "frappe"
preferred-dark-theme = "frappe"
smart-punctuation = true
git-repository-url = "https://github.com/Pistonite/workex"
additional-css = [
    "./theme/extra-css/catppuccin.css", 
    "./theme/extra-css/patch.css", 
]
