version: '3'

includes:
  mdbook:
    taskfile: ../../node_modules/mono-dev/task/mdbook.yaml
    optional: true
    internal: true

tasks:
  install:
    cmds:
      - task: mdbook:install-theme
        vars:
          MONO_DEV: ../../node_modules/mono-dev

  dev:
    desc: Start mdbook in watch mode
    cmds:
      - rm -rf book
      - shwoop book -w src --host -- {{.TASK_EXE}} build-dev

  build-dev:
    - txtpp -r -N src
    - mdbook build

  build:
    desc: (Re-)build the book
    cmds:
      - rm -rf book
      - txtpp -r src
      - mdbook build



