minimumReleaseAgeExclude:
  - '@pistonite/*'

packages:
  - packages/sdk
  - packages/mono-dev
  - packages/example-multiwindow
  - packages/example-tutorial

catalog:
  "@pistonite/pure": ^0.29.8
  mono-dev: github:pistonight/mono-dev#dist
