version: '3'

tasks:
  check:
    desc: Check for issues
    vars:
      CLIPPY_ARGS: -D warnings -D clippy::todo
    cmds:
    - cargo clippy --all-features --all-targets -- {{.CLIPPY_ARGS}}
    - cargo fmt --check

  fix:
    desc: Run formatter
    cmds:
    - cargo fmt

  run:
    desc: Run with test inputs
    cmds:
    - cargo run -- -p testproto test/input.ts test/Bar.ts
    - npx tsc
