version: '3'

includes:
  test:
    taskfile: ./packages/test
    dir: ./packages/test

  ts-sdk:
    taskfile: ./packages/ts-sdk
    dir: ./packages/ts-sdk

  doc:
    taskfile: ./packages/doc
    dir: ./packages/doc

tasks:
  install-extra-cargo-tools:
    aliases: [iects]
    desc: Install extra development tools needed
    cmds:
      - cargo install txtpp mdbook mdbook-admonish live-server magoo

  install:
    desc: Install dependencies
    cmds:
      - magoo install
      - pnpm install

  install-ci:
    cmds:
      - pnpm install --frozen-lockfile

  check:
    desc: Check for issues
    vars:
      CLIPPY_ARGS: -D warnings -D clippy::todo
    cmds:
      - cargo clippy --all-features --all-targets -- {{.CLIPPY_ARGS}}
      - cargo fmt --check

  fix:
    desc: Run formatter
    cmds:
      - cargo fmt

