version: '3'

includes:
  cli:
    taskfile: ./packages/cli
    dir: ./packages/cli

  test:
    taskfile: ./packages/test
    dir: ./packages/test

  ts-sdk:
    taskfile: ./packages/ts-sdk
    dir: ./packages/ts-sdk

  doc:
    taskfile: ./packages/doc
    dir: ./packages/doc

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install txtpp mdbook mdbook-admonish live-server magoo

  install:
    cmds:
      - magoo install
      - pnpm install
      - task: post-install

  install-ci:
    cmds:
      - pnpm install --frozen-lockfile
      - task: post-install

  post-install:
    cmds:
      - task: doc:install
      - task: ts-sdk:install
      
  check:
    cmds:
      - task: cli:check
      - task: ts-sdk:check

  test:
    cmds:
      - task: test:run

  typedoc:
    cmds:
      - pnpm exec typedoc

  serve:
    deps: [typedoc]
    cmds:
      - pnpm exec serve docs

  build-doc:
    cmds:
      - task: doc:build
      - task: typedoc
      - cp -r docs packages/doc/book


