version: '3'

includes:
  common:
    taskfile: ./node_modules/mono-dev/task/common.yaml
    optional: true
    flatten: true

  cli:         { taskfile: ./packages/cli,              dir: ./packages/cli,              internal: true }
  ex-tutorial: { taskfile: ./packages/example-tutorial, dir: ./packages/example-tutorial, internal: true }
  ex-multiwindow: { taskfile: ./packages/example-multiwindow, dir: ./packages/example-multiwindow, internal: true }
  sdk:         { taskfile: ./packages/sdk,              dir: ./packages/sdk,              internal: true }
  doc:         { taskfile: ./packages/doc,              dir: ./packages/doc,              internal: true }

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: txtpp mdbook mdbook-admonish shwoop

  install:
    - pnpm install
    - task: post-install

  post-install:
    - task: doc:install
    - task: sdk:install
      
  check:
    - task: sdk:build
    - task: cli:check
    - task: sdk:check
    - task: ex-multiwindow:generate
    - task: ex-multiwindow:check

  test:
    - task: ex-tutorial:gen

  build-doc:
    - task: doc:build
    - task: sdk:doc
    - cp -r packages/sdk/docs packages/doc/book

  publish:
    - task: sdk:publish


  upgrade:
    - pnpm up -r mono-dev @pistonite/pure
    - cargo upgrade
    - pnpm dedupe
    - pnpm dedupe --check


