version: '3'

includes:
  common:
    taskfile: ./packages/mono-dev/task/common.yaml
    flatten: true

  cli:
    taskfile: ./packages/cli
    dir: ./packages/cli

  ex-tutorial:
    taskfile: ./packages/example-tutorial
    dir: ./packages/example-tutorial

  ex-multiwindow:
    taskfile: ./packages/example-multiwindow
    dir: ./packages/example-multiwindow

  sdk:
    taskfile: ./packages/sdk
    dir: ./packages/sdk

  doc:
    taskfile: ./packages/doc
    dir: ./packages/doc

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install txtpp mdbook mdbook-admonish live-server magoo cargo-watch

  install:
    cmds:
      - magoo install
      - pnpm install
      - task: post-install

  install-ci:
    cmds:
      - pnpm install --frozen-lockfile
      - task: post-install

  post-install:
    cmds:
      - task: doc:install
      - task: sdk:install
      
  check:
    cmds:
      - task: cli:check
      - task: sdk:check
      - task: ex-multiwindow:generate
      - task: ex-multiwindow:check

  test:
    cmds:
      - task: ex-tutorial:gen

  typedoc:
    cmds:
      - pnpm exec typedoc

  serve:
    deps: [typedoc]
    cmds:
      - pnpm exec serve docs

  build-doc:
    cmds:
      - task: doc:build
      - task: typedoc
      - cp -r docs packages/doc/book


