version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true

tasks:
  install:
    - task: ecma:config
  check:
    - task: ecma:check
  fix:
    - task: ecma:fix
  build:
    - task: ecma:lib-build
  doc:
    - task: ecma:doc-build
  dev-doc:
    - task: ecma:doc-dev

  publish:
    - rm -rf dist
    - task: check
    - task: build
    - task: ecma:publish
