version: '3'

tasks:
  run:
    desc: Build and serve the example
    cmds:
      - cargo run -- -p app src/msg/proto.ts
      - bunx tsc
      - mkdir -p dist
      - bun build src/app.ts --outfile dist/app.js --minify
      - bun build src/worker.ts --outfile dist/worker.js --minify
      - bunx serve .

  check:
    desc: Check for issues
    cmds:
      - bunx prettier . --check

  fix:
    desc: Run formatter
    cmds:
      - bunx prettier . --write
