name: "Workflow Setup"
description: "Workflow Setup"

inputs:
  token:
    description: "GitHub Token"
    required: true
  rust_targets:
    description: "Targets for rust-toolchain"
    default: ""

runs:
  using: composite
  steps:
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ inputs.token }}

    # js stuff
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v4 # useblacksmith/setup-node@v5
      with:
        node-version: 22
        cache: 'pnpm'
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.rust_targets }}
    - uses: Swatinem/rust-cache@v2 # useblacksmith/rust-cache@v3
