version: '3'

tasks:
  dev:
    desc: Start mdbook in watch mode
    cmds:
      - task: build
      - live-server book -p 8081 {{.CLI_ARGS}} &
      - cargo watch -s "txtpp -r -N doc/src && mdbook build doc"

  build:
    desc: (Re-)build the book
    cmds:
      - rm -rf book
      - txtpp -r src
      - mdbook build
