version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  install:
    cmds:
      - task: ecma:mono-config

  check:
    desc: Run checks
    cmds:
      - task: ecma:mono-check

  fix:
    desc: Fix formatting and other check issues
    cmds:
      - task: ecma:mono-fix

  publish:
    cmds:
      - pnpm publish --access public
