[package]
name = "workex"
version = "0.1.3"
edition = "2024"
description = "In-house messaging bindgen library for workers/windows"
repository = "https://github.com/Pistonite/workex"
license = "MIT"
authors = ["Pistonight <pistonknight@outlook.com>"]
exclude = [
    "Taskfile.yml",
]

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
codize = "0.3.3"
derive_more = { version = "2.0.1", features = ["deref", "deref_mut"] }
dunce = "1.0.5"
swc_common = { version = "14.0.1", features = ["tty-emitter"] }
swc_core = { version = "33.0.2", features = ["ecma_ast"] }
swc_ecma_parser = "21.0.0"

[package.metadata.binstall.signing]
algorithm = "minisign"
pubkey = "RWThJQKJaXayoZBe0YV5LV4KFkQwcqQ6Fg9dJBz18JnpHGdf/cHUyKs+"
