version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  build:
    deps: [generate]
    cmds:
      - bun build src/main.ts > dist/index.js

  serve:
    deps: [build]
    cmds:
      - bun run server.ts

  install:
    cmds:
      - task: generate
      - task: ecma:mono-config

  generate:
    cmds:
      - cargo run --bin workex -- -p multiwindow -l SideA,SideB src/proto.ts

  check:
    cmds:
      - task: ecma:mono-check

  fix:
    cmds:
      - task: ecma:mono-fix
