name: Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build, Check, Run Test Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - run: task check
      - run: task test:ci
      - run: task test:run -- --release

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo-binstall --no-confirm mdbook mdbook-admonish txtpp
      - run: task doc:build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: doc/book
          retention-days: 3

  deploy-docs:
    name: Deploy Docs
    needs:
      - docs
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
